Fixed broken titles and links
wordpress-mobile/objective-c-style-guide pull request #2
Opened 2018-01-10 13:35 UTC by Dassine

The google and apple links were broken as well as the indentation style of some titles. Thanks for reviewing it.

2019-02-15 19:42 UTC, shiki requested changes
Thank you for contributing! If you don't mind fixing the indentations, we can take a look again 🙂

2019-02-15 19:42 UTC, shiki commented on README.md
> +rect:(NSRect)theRect
It looks like this and a few other lines' indentations were accidentally changed. Were these intentional?

2019-02-19 19:03 UTC, Dassine commented
@shiki unfortunately I don't have access to my branch :)

2019-02-22 19:57 UTC, shiki commented
@Dassine No worries. I'm closing this and applied your commits on a separate PR: #3.

2019-02-22 19:57 UTC, closed without merging